services:
  dataspace-connector:
    container_name: dataspace-connector
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        ENV: ${NODE_ENV}
    restart: unless-stopped
    tty: true
    volumes:
      - './src/:/usr/src/app/src'
    ports:
      - 3002:${PORT}
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - dataspace-connector

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: dataspace-connector
    restart: unless-stopped
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - dataspace-connector

networks:
  dataspace-connector:
    external: false
