export enum DataExchangeStatusEnum {
    EXPORT_SUCCESS = 'EXPORT_SUCCESS',
    IMPORT_SUCCESS = 'IMPORT_SUCCESS',
    PROVIDER_EXPORT_ERROR = 'PROVIDER_EXPORT_ERROR',
    CONSUMER_IMPORT_ERROR = 'CONSUMER_IMPORT_ERROR',
    UNDEFINED_ERROR = 'UNDEFINED_ERROR',
}
