name: Test Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      branchName:
        required: true
      instanceName:
        required: true

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch: ${{ github.event.inputs.branchName }}"
      - run: echo "Instance: ${{ github.event.inputs.instanceName }}"
