name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "Nom de la branche à déployer"
        required: true
      instanceName:
        description: "Nom de l'instance"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher inputs
        run: |
          echo "Branch: ${{ github.event.inputs.branchName }}"
          echo "Instance: ${{ github.event.inputs.instanceName }}"